# Generated by Django 2.1.4 on 2021-05-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
    ]
